---
# defaults file for kerberos
kerberos_hostname: "kerberos"
kerberos_ip: "172.19.1.190"
kerberos_realm: david.com
kerberos_name: "{{ kerberos_hostname }}.{{ kerberos_realm }}"
kadmin_user: "root"
kadmin_password: "cambiar"