---
# defaults file for hdfs-singlemode
user_name: "hadoop"
group_name: "hadoop"
user_password: "hadoop"
hdfs_folder: "/hdfs"
java_download_url: "http://javadl.oracle.com/webapps/download/AutoDL?BundleId=227541_e758a0de34e24606bca991d704f6dcbf"