---
# defaults file for hdfs-singlemode
user_name: "hadoop"
group_name: "hadoop"
user_password: "hadoop"
hdfs_folder: "/hdfs"
java_download_url: "http://javadl.oracle.com/webapps/download/AutoDL?BundleId=227541_e758a0de34e24606bca991d704f6dcbf"
java_rpm_name: "jdk-8u151-linux-x64.rpm"
hadoop_package: "hadoop-2.9.0"
hadoop_download_url: "http://mirror.rise.ph/apache/hadoop/common/stable/{{ hadoop_package }}.tar.gz"
hadoop_directory: "/opt/hadoop"
zookeeper_package: "zookeeper-3.4.10"
zookeeper_download_url: "http://apache.rediris.es/zookeeper/stable/{{ zookeeper_package }}"
zookeeper_directory: "/opt/zookeeper"