# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

cluster={
  "hdfs1" => {
    :box => "centos/7",
    :ram => 2048,
    :cpu => 1
  },
  "hdfs2" => {
    :box => "centos/7",
    :ram => 2048,
    :cpu => 1
  },
  "hdfs3" => {
    :box => "centos/7",
    :ram => 2048,
    :cpu => 1
  }
}

Vagrant.configure("2") do |config|
  cluster.each_with_index do |(hostname, machine), index|
    config.vm.define hostname do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = hostname
      node.vm.network "public_network", bridge: "1"
      node.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
        vb.customize ["modifyvm", :id, "--cpus", machine[:cpu]]
      end # end customize

   if index == cluster.size - 1
     config.vm.provision :ansible do |ansible|
       ansible.limit = 'all'
       ansible.playbook = "playbook-hdfs.yml"
       ansible.groups = {
         "hdfsnamenodes" => ["hdfs1","hdfs2"],
         "hdfsdatanodes" => ["hdfs3"],
         "hdfsjournalnodes" => ["hdfs1","hdfs2","hdfs3"],
         "hdfszookeepers" => ["hdfs1","hdfs2","hdfs3"],
       }
       ansible.host_vars = {
         "hdfs1" => {
           "zookeeperid" => "1"
         },
         "hdfs2" => {
           "zookeeperid" => "2"
         },
         "hdfs3" => {
           "zookeeperid" => "3"
         }
       }
     end # end provision
   end # end if
    end # end config
  end # end cluster
end # end vagrant
