---
# defaults file for hdfs-singlemode
user_name: "hadoop"
group_name: "hadoop"
user_password: "hadoop"
hdfs_folder: "/hdfs"
java_download_url: "http://javadl.oracle.com/webapps/download/AutoDL?BundleId=227541_e758a0de34e24606bca991d704f6dcbf"
java_rpm_name: "jdk-8u151-linux-x64.rpm"
hadoop_package: "hadoop-2.9.0"
hadoop_download_url: "http://mirror.rise.ph/apache/hadoop/common/stable/{{ hadoop_package }}.tar.gz"
hadoop_directory: "/opt/hadoop"
hadoop_log_directory: "/opt/hadoop/logs"
zookeeper_package: "zookeeper-3.4.10"
zookeeper_download_url: "http://apache.rediris.es/zookeeper/stable/{{ zookeeper_package }}.tar.gz"
zookeeper_directory: "/opt/zookeeper"
datanode_directory: "{{ hdfs_folder }}/datanode"
namenode_directory: "{{ hdfs_folder }}/namenode"
journalnode_directory: "{{ hdfs_folder }}/journalnode"
name_hdfs_cluster: "mycluster"
hdfs_tmp_directory: "{{hdfs_folder}}/tmp"
listening_address: 0.0.0.0

kerberos_securize: true
kerberos_name: "kerberos.david.com"
kerberos_ip: "192.192.192.192"
kerberos_realm: PERFORMANCE.DAVID.COM